terList = [
    'INT'       ,
    'VOID'      ,
    'ID'        ,
    'LPAR'      ,
    'RPAR'      ,
    'LBR'       ,
    'RBR'       ,
    'SEMICOL'   ,
    'ASSIGN'    ,
    'RETURN'    ,
    'WHILE'     ,
    'IF'        ,
    'ELSE'      ,
    'RELOP'     ,
    'ADD'       ,
    'SUB'       ,
    'MULT'      ,
    'DIV'       ,
    'VALUE'     ,
]